extends Object
## One-line UI help for **`SimParams`** property names (see **`constants.gd`**). Unknown keys fall back to a generic string.

const _TEXT: Dictionary = {
	"MM_PER_UNIT": "Read-only: same as GRAIN_SIZE_MM (mm per world unit).",
	"TICKS_PER_ANT_DAY": "Read-only: real-time seconds per ant-day × physics tick rate.",
	"EGG_DURATION_TICKS": "Read-only: EGG_DURATION_DAYS × TICKS_PER_ANT_DAY.",
	"LARVA_DURATION_TICKS": "Read-only: LARVA_DURATION_DAYS × TICKS_PER_ANT_DAY.",
	"PUPA_DURATION_TICKS": "Read-only: PUPA_DURATION_DAYS × TICKS_PER_ANT_DAY.",
	"QUEEN_CLAUSTRAL_EGG_INTERVAL_TICKS": "Read-only: claustral egg interval in ticks.",
	"QUEEN_ESTABLISHED_EGG_INTERVAL_TICKS": "Read-only: established egg interval in ticks.",
	"QUEEN_CLAUSTRAL_ENERGY_DRAIN_PER_TICK": "Read-only: queen energy drain per tick during claustral phase.",
	"YOUNG_WORKER_AGE_THRESHOLD": "Read-only: age in ticks below which workers are interior-only.",
	"CALLOW_DARKEN_TICKS": "Read-only: ticks for callow color darkening.",
	"FOOD_SPOIL_DURATION_TICKS_MIN": "Read-only: minimum spoil duration in ticks.",
	"FOOD_SPOIL_DURATION_TICKS_MAX": "Read-only: maximum spoil duration in ticks.",
	"GRAIN_SIZE_MM": "Millimetres represented by one world unit; matches grain-scale fiction (worker body length is many units).",
	"BLOCK_AIR": "Block id for air (world voxel type).",
	"BLOCK_SAND": "Block id for loose sand.",
	"BLOCK_STONE": "Block id for immovable stone.",
	"BLOCK_PACKED_SAND": "Block id for compacted nest sand (harder to dig).",
	"SAND_LATERAL_SPILL_STACK_LIMIT": "Loose sand column height above which lateral spill runs each sand step.",
	"NEST_SPILL_LATERAL_EXCLUDE_RADIUS": "Surface columns within this radius of the nest mouth skip lateral sand spill (keeps shaft clearer).",
	"WORKER_FOOD_STORE_DEPOSIT_MAX_H_DIST": "Horizontal distance from nest entrance (xz) at which returning workers credit colony food stores (shaft mouth).",
	"WORKER_ENTRANCE_CLEAR_ENGAGE_DIST": "Workers within this distance may start digging to clear a blocked nest shaft.",
	"TICKS_PER_GAME_SECOND": "Physics ticks counted as one game second (usually 1:1 with engine ticks).",
	"GAME_SECONDS_PER_ANT_DAY": "Real-time seconds per simulated ant-day (drives calendar and derived tick durations).",
	"GAME_DAYS_PER_ANT_WEEK": "Days per in-game week (calendar helper).",
	"EGG_DURATION_DAYS": "Simulated days an egg takes before hatching (scaled to ticks via ant-day length).",
	"LARVA_DURATION_DAYS": "Simulated days a larva develops before pupation.",
	"PUPA_DURATION_DAYS": "Simulated days a pupa develops before eclosion.",
	"QUEEN_CLAUSTRAL_EGG_BATCH_MIN": "Minimum eggs per claustral batch (founding phase).",
	"QUEEN_CLAUSTRAL_EGG_BATCH_MAX": "Maximum eggs per claustral batch (founding phase).",
	"QUEEN_EGG_CANNIBAL_ENERGY_GAIN": "Queen energy gained when consuming a trophic egg.",
	"QUEEN_LARVA_FEED_ENERGY_COST": "Energy cost to the queen per tick when feeding larvae.",
	"QUEEN_LARVA_FEED_PER_TICK": "Base larva feeding throughput per tick (colony-level).",
	"QUEEN_LARVA_FEED_ENERGY_PER_LARVA_PER_TICK": "Extra queen energy cost per larva per tick (if used).",
	"WORKER_BROOD_CARE_PER_TICK": "Abstract brood-care intensity applied per tick (nanitic/worker care).",
	"QUEEN_TROPHALLAXIS_BASE_PER_TICK": "Baseline food mass drawn from stores per tick toward queen energy (established colony).",
	"QUEEN_TROPHALLAXIS_PER_WORKER_SQRT": "Extra trophallaxis mass scaled by sqrt(worker count).",
	"QUEEN_TROPHALLAXIS_SUGAR_FRACTION": "Fraction of trophallaxis want taken from sugar vs protein.",
	"QUEEN_TROPHALLAXIS_PROTEIN_FRACTION": "Fraction of trophallaxis want taken from protein vs sugar (should complement sugar).",
	"QUEEN_TROPHALLAXIS_ENERGY_PER_UNIT_FOOD": "Queen energy gained per unit mass moved from stores via trophallaxis.",
	"QUEEN_VISUAL_SCALE": "Godot scale of the queen mesh in colony view.",
	"WORKER_VISUAL_SCALE": "Godot scale of normal worker meshes.",
	"NANITIC_VISUAL_SCALE": "Godot scale of first nanitic workers.",
	"PHEROMONE_CELL_SIZE": "World voxels per side of one 2D recruitment-trail grid cell.",
	"PHEROMONE_BASE_DEPOSIT": "Scale for ant-laid recruitment deposit each return step (with beacon and per-step fraction).",
	"PHEROMONE_DEPOSIT_AMOUNT": "Burst recruitment deposit at food pickup (scaled by quality and saturation).",
	"PHEROMONE_EVAPORATION_RATE": "Multiplicative factor per chemistry pass on trail cells (<1 = decay).",
	"PHEROMONE_DIFFUSION_LAMBDA": "Laplacian diffusion strength between trail cells each evaporation pass.",
	"PHEROMONE_EVAPORATION_INTERVAL_TICKS": "Physics ticks between trail diffusion+evaporation passes.",
	"PHEROMONE_RECRUIT_THRESHOLD": "Minimum trail concentration for sensing/foraging recruit mode and trail detection.",
	"PHEROMONE_MINIMUM_THRESHOLD": "Trail cells below this concentration after decay are removed from the grid.",
	"PHEROMONE_SENSE_RADIUS": "Voxel Chebyshev radius for scouts detecting whether a recruitment trail is present.",
	"PHEROMONE_TROPOTAXIS_FLOOR": "Minimum roulette weight in recruit tropotaxis when trail differences are tiny.",
	"TRAIL_SATIATED_DEPOSIT_PROBABILITY": "Chance to apply pickup burst at food when taking load (Bernoulli).",
	"RECRUIT_TRAIL_PER_STEP_FRACTION": "Fraction of beacon-scaled base applied each step while returning with food (continuous trail).",
	"RECRUIT_TRAIL_FOLLOW_LOCAL_RADIUS": "Neighborhood radius (voxels) used to judge if recruit mode should drop to scout (local trail max).",
	"RECRUIT_TRAIL_EXIT_SCOUT_FACTOR": "Recruit mode exits when local max trail < recruit threshold × this factor.",
	"PHEROMONE_EXPLOITATION_THRESHOLD": "Footprint/trail crossover: above this trail level, exploitation-phase footprint rules apply.",
	"FOOTPRINT_SEARCH_ATTRACTION_WEIGHT": "Scout search-phase weight on moving toward lower explored footprint (positive chemotaxis).",
	"FEEDER_CROWD_RADIUS": "Chebyshev radius around a food patch center for counting crowding workers.",
	"FEEDER_CROWD_MAX_WORKERS": "Above this many workers near a patch, new pickups often skip (overflow).",
	"FEEDER_CROWD_OVERFLOW_ATTEMPT_PROB": "Chance to still attempt pickup when at/over crowding limit.",
	"FORAGING_MEMORY_TRAIL_WEAK": "If trail is weaker than this, experienced foragers bias steps toward remembered food coordinates.",
	"FORAGING_MEMORY_BIAS_WEIGHT": "Strength of memory alignment bonus when trail is weak.",
	"TROPOTAXIS_RATIO_EPS": "Small epsilon in recruit tropotaxis ratio (trail+ε)/(denom+ε) for numerical stability.",
	"TROPOTAXIS_RATIO_GAIN": "Gain on trail/footprint ratio term in recruit tropotaxis neighbor weights.",
	"TROPOTAXIS_HC_DENOM_SCALE": "Scales footprint sum in the tropotaxis denominator (CHC load).",
	"TROPOTAXIS_CROWD_PER_ANT": "Crowding penalty weight per neighbor worker in tropotaxis denominator.",
	"RECRUIT_TRAIL_BEACON_EXTRA_MULT": "Extra recruitment deposit multiplier near the food source (exponential falloff).",
	"RECRUIT_TRAIL_BEACON_DECAY_MM": "E-fold distance (mm) for beacon falloff from remembered patch center.",
	"RECRUIT_TRAIL_BEACON_FLOOR": "Minimum beacon multiplier far from food (keeps weak trail away from patch).",
	"HOME_RANGE_FOOTPRINT_THRESHOLD": "Footprint concentration treated as well-trodden home-range substrate (faster scout/recruit steps).",
	"FORAGING_MARKED_INTERVAL_MULT": "Move interval multiplier on marked substrate (<1 = faster steps).",
	"NAIVE_ZIGZAG_INTERVAL_MIN": "Naive workers on unmarked substrate: random lower bound on interval stretch.",
	"NAIVE_ZIGZAG_INTERVAL_MAX": "Naive workers on unmarked substrate: random upper bound on interval stretch.",
	"SCOUT_SEARCH_STOP_PROBABILITY": "Per step, chance a scout pauses in place (substrate sampling).",
	"VALIDATION_EXPORT_ENABLED": "Append CSV validation logs under user:// when true.",
	"VALIDATION_EXPORT_INTERVAL_TICKS": "Ticks between validation CSV rows.",
	"ALARM_DEPOSIT_ON_CRITICAL": "Alarm pheromone deposit scale when food-critical events fire near nest.",
	"ALARM_EVAPORATION_RATE": "Per-interval multiplier on alarm field concentration.",
	"ALARM_EVAPORATION_INTERVAL_TICKS": "Ticks between alarm evaporation passes.",
	"ALARM_MINIMUM_THRESHOLD": "Alarm cells below this are pruned.",
	"PHEROMONE_VIS_RECRUITMENT": "Overlay color for recruitment trail ([P] view).",
	"PHEROMONE_VIS_FOOTPRINT": "Overlay color for CHC footprint ([P] view).",
	"FOOTPRINT_OVERLAY_MIN_CONC": "Minimum footprint concentration to draw a footprint overlay quad.",
	"PHEROMONE_VIS_BUILDING": "Overlay color for nest-construction pheromone ([P] view).",
	"PHEROMONE_VIS_ALARM": "Overlay color for alarm field ([P] view).",
	"TRAIL_SATURATION_START": "Local trail concentration above which recruitment deposits scale down (negative feedback).",
	"TRAIL_SATURATION_MIN_DEPOSIT_SCALE": "Minimum deposit multiplier at full trail saturation.",
	"FOOTPRINT_DEPOSIT_PER_STEP": "Passive CHC deposited per worker step onto footprint grid.",
	"FOOTPRINT_EVAPORATION_RATE": "Per-pass multiplier on footprint concentration.",
	"FOOTPRINT_EVAPORATION_INTERVAL_TICKS": "Ticks between footprint evaporation passes.",
	"FOOTPRINT_MINIMUM_THRESHOLD": "Footprint cells below this after decay are removed.",
	"FOOTPRINT_REPULSION_WEIGHT": "Weight on footprint gradient (negative feedback / exploration) in scout exploration.",
	"FOOTPRINT_SCOUT_BASE_WEIGHT": "Base roulette weight for random component in footprint-biased scout steps.",
	"FOOTPRINT_SCOUT_REPULSION_MULT": "Multiplier on footprint repulsion term for scouts.",
	"FOOD_STORE_TARGET_SUGAR": "Soft target for colony sugar store (task assignment / HUD scaling).",
	"FOOD_STORE_TARGET_PROTEIN": "Soft target for colony protein store (task assignment / HUD scaling).",
	"MIN_FORAGER_FRACTION": "Minimum fraction of idle workers assigned toward foraging when possible.",
	"SCOUT_MAX_TURN_DEG_PER_STEP": "Cap on heading change per step for scouting-related movement.",
	"SCOUT_MIN_SEARCH_RADIUS": "Minimum distance from nest for some scout behaviors (if used).",
	"FOOD_CARRY_AMOUNT": "Mass credited to stores and taken from a patch per successful foraging trip.",
	"FOOD_APHID_SUPPLY_MIN": "Random minimum initial supply for aphid-style sugar patches.",
	"FOOD_APHID_SUPPLY_MAX": "Random maximum initial supply for aphid-style sugar patches.",
	"FOOD_INSECT_SUPPLY_MIN": "Random minimum initial supply for insect protein patches.",
	"FOOD_INSECT_SUPPLY_MAX": "Random maximum initial supply for insect protein patches.",
	"FOOD_SEED_SUPPLY_MIN": "Random minimum initial supply for seed sugar patches.",
	"FOOD_SEED_SUPPLY_MAX": "Random maximum initial supply for seed sugar patches.",
	"FOOD_SPAWN_FIRST_DELAY_MIN": "Minimum ticks before first surface food spawn attempt.",
	"FOOD_SPAWN_FIRST_DELAY_MAX": "Maximum ticks before first surface food spawn attempt.",
	"FOOD_SPAWN_INTERVAL_TICKS_MIN": "Minimum ticks between automatic food spawn attempts.",
	"FOOD_SPAWN_INTERVAL_TICKS_MAX": "Maximum ticks between automatic food spawn attempts.",
	"FOOD_MAX_ACTIVE_SOURCES": "Cap on simultaneous active food patches in the world.",
	"FOOD_SPAWN_MIN_DIST_FROM_NEST": "Minimum horizontal distance from nest entrance for spawning new food.",
	"FOOD_VISUAL_BASE_SCALE_MIN": "Random lower bound for food patch visual root scale.",
	"FOOD_VISUAL_BASE_SCALE_MAX": "Random upper bound for food patch visual root scale.",
	"FOOD_VISUAL_MIN_SCALE_RATIO": "Minimum visual scale ratio when supply is nearly depleted.",
	"FOOD_CRITICAL_THRESHOLD": "Store level below which food-critical alarm logic may trigger.",
	"COMPACTION_RADIUS": "Radius in voxels for compacting loose sand to packed sand when air opens.",
	"PACKED_SAND_DIG_MULTIPLIER": "Dig duration multiplier for packed sand vs loose sand.",
	"PACKED_SAND_COLOR": "Albedo tint for packed sand meshes.",
	"DIG_ACT_DURATION_TICKS": "Base ticks to remove one diggable voxel (sand) in worker dig state.",
	"TUNNEL_YIELD_TICKS": "Ticks of sand physics yield after a dig completes (if used).",
	"SPOIL_DEPOSIT_RADIUS": "Horizontal disk radius for queen/worker spoil placement around nest entrance.",
	"SPOIL_DEPOSIT_INNER_CLEAR": "Inner clearance from center for random spoil disk samples.",
	"MAX_SPOIL_HEIGHT": "Maximum surface height above baseline for accepting spoil placement.",
	"MAX_NEST_BUILDERS": "Maximum workers simultaneously in nest-building/digging roles.",
	"VOLUME_PER_WORKER": "Target nest air volume per worker for dig assignment heuristics.",
	"MAX_DIG_DEPTH": "Maximum vertical depth (voxels) nest digging may consider below surface.",
	"MIN_GALLERY_WIDTH": "Blueprint minimum gallery width (voxels).",
	"MIN_GALLERY_HEIGHT": "Blueprint minimum gallery height (voxels).",
	"MIN_SHAFT_WIDTH": "Minimum shaft width for blueprint geometry.",
	"MIN_BROOD_CHAMBER_DIAMETER": "Minimum brood chamber diameter for blueprints.",
	"QUEEN_CHAMBER_DIAMETER": "Default queen chamber diameter (blueprint / scoring).",
	"QUEEN_CHAMBER_HEIGHT": "Default queen chamber height.",
	"QUEEN_PERMANENT_CHAMBER_DIAMETER": "Larger permanent chamber diameter where applicable.",
	"SHAFT_TARGET_DEPTH": "Target shaft depth (voxels) before lateral gallery scoring dominates.",
	"DEPTH_WEIGHT_ENTRY": "Scoring weight per voxel depth for digging downward near the shaft.",
	"DEPTH_WEIGHT_CHAMBER": "Bonus weight for chamber-depth alignment in dig scoring.",
	"DEPTH_ATTRACTION_FALLOFF": "Falloff for depth attraction in dig target scoring.",
	"MAX_GALLERY_RADIUS": "Approximate max horizontal reach for lateral nest expansion scoring.",
	"HORIZONTAL_WEIGHT": "Weight for horizontal expansion in dig scoring.",
	"TUNNEL_CONTINUE_BONUS": "Bonus when continuing an existing tunnel (few adjacent air faces).",
	"CROWDING_PENALTY": "Penalty when many diggers target similar regions (if used).",
	"NOISE_AMPLITUDE": "Random jitter amplitude in dig target scoring.",
	"BLUEPRINT_WEIGHT": "Extra weight when blueprint gallery leads are attractive.",
	"RADIAL_OUTWARD_BIAS": "Bias for outward radial expansion from chamber center.",
	"TUNNEL_EXTEND_BIAS": "Bonus for extending tunnel fronts.",
	"NEST_SHAFT_AXIS_RADIUS_VOX": "Horizontal radius treated as vertical shaft axis (entry pull damped inside).",
	"NEST_SHAFT_AXIS_ENTRY_PULL_SCALE": "Multiplier on entry pull when shaft is deep enough and voxel is on-axis.",
	"NEST_LATERAL_MIN_AXIS_DIST": "Minimum horizontal distance from axis to count as lateral expansion.",
	"NEST_LATERAL_EXPANSION_BONUS": "Score bonus for lateral digs past the minimum axis distance.",
	"NEST_DEEPEN_BELOW_DEEPEST_PENALTY": "Penalty for deepening the narrow shaft below current deepest air.",
	"NEST_GALLERY_BRANCH_NOISE": "Random branch noise for gallery dig sampling.",
	"NEST_GALLERY_SAMPLE_BOOST": "Extra dig-front samples when shaft is deep enough (performance cap).",
	"NEST_SUBSTRATE_HARDNESS_MIN": "Lower bound multiplier on dig duration (substrate hash).",
	"NEST_SUBSTRATE_HARDNESS_MAX": "Upper bound multiplier on dig duration (substrate hash).",
	"NEST_BLUEPRINT_DIST_MIN": "Minimum distance from origin for blueprint placement jitter.",
	"NEST_BLUEPRINT_DIST_MAX": "Maximum distance from origin for blueprint placement jitter.",
	"NEST_BLUEPRINT_GLOBAL_ROT_MAX": "Maximum global rotation for blueprint gallery (radians).",
	"NEST_BLUEPRINT_ANGLE_JITTER": "Angular jitter for blueprint gallery orientation.",
	"NEST_BLUEPRINT_SPUR_PROB": "Probability of spur galleries in blueprint scoring.",
	"NEST_BLUEPRINT_LEAD_WEIGHT": "Weight for nest_builder lead scoring on dig candidates.",
	"BUILD_PHEROMONE_DEPOSIT_AMOUNT": "Construction pheromone deposited per sand voxel placed.",
	"BUILD_PHEROMONE_EVAPORATION_RATE": "Per-interval decay factor on construction pheromone voxels.",
	"BUILD_PHEROMONE_EVAPORATION_INTERVAL_TICKS": "Ticks between construction pheromone evaporation passes.",
	"BUILD_PHEROMONE_MINIMUM": "Minimum construction concentration before cells are pruned.",
	"FOUNDING_SHAFT_DEPTH": "Vertical depth of founding shaft excavation (voxels).",
	"FOUNDING_SHAFT_WIDTH": "Horizontal width of founding shaft footprint (voxels).",
	"FOUNDING_CHAMBER_SIZE": "Initial chamber size (Vector3i) for founding.",
	"QUEEN_BFS_AIR_MAX_NODES": "Max BFS nodes when queen searches air connectivity.",
	"PATH_TO_SURFACE_MAX_STEPS": "Max steps when building a path to surface for dug workers.",
	"QUEEN_SPOIL_DEPOSIT_SAMPLES": "Samples for queen spoil disk placement scoring.",
	"TRAIL_COVER_BUILD_PROB": "Probability workers try trail-covering nest build when eligible.",
	"XRAY_SAND_ALPHA": "Alpha for loose sand when [X] x-ray terrain is on.",
	"XRAY_DEPTH_FADE_RANGE": "Depth range for x-ray fade (if used).",
	"FAST_FORWARD_SIM_STEPS_CAP": "Upper cap on simulation sub-steps per frame when fast-forwarding.",
	"SIM_SUBSTEP_THROTTLE_MIN_WORKERS": "Worker count at which sub-step throttling may activate.",
	"SIM_SUBSTEP_WORKER_BUDGET": "Approximate tick budget for ant steps; divided by worker count for throttle.",
	"SIM_SUBSTEP_MIN": "Minimum sub-steps per frame when throttling.",
	"PHEROMONE_MAX_DIFFUSION_PASSES_PER_FRAME": "Max full diffusion passes per frame on trail chemistry (batched ticks).",
	"TRAIL_OVERLAY_REFRESH_BASE": "Base frames between pheromone overlay mesh rebuilds.",
	"TRAIL_OVERLAY_REFRESH_SLOW": "Slower overlay refresh when many workers or high fast-forward.",
	"TRAIL_OVERLAY_THROTTLE_WORKER_THRESHOLD": "Worker count above which overlay uses slow refresh.",
	"WORKER_MOVE_INTERVAL": "Seconds between worker movement steps at 1× speed (scaled by fast-forward).",
	"QUEEN_SEARCH_MOVE_INTERVAL": "Queen movement interval during surface search phase.",
	"QUEEN_DIG_ACT_TICK_INTERVAL": "Timing for queen digging actions.",
	"QUEEN_FLY_IN_DURATION": "Seconds for queen fly-in animation phase.",
	"QUEEN_WING_SHED_DURATION": "Seconds for wing shed phase.",
	"QUEEN_SEARCH_DURATION_MIN": "Minimum duration of queen surface search (seconds).",
	"QUEEN_SEARCH_DURATION_MAX": "Maximum duration of queen surface search (seconds).",
	"FAST_FORWARD_SPEEDS": "Ordered multipliers for [F] fast-forward tiers (Engine.time_scale).",
}


static func help_for(param_name: String) -> String:
	var s: Variant = _TEXT.get(param_name, null)
	if s is String and not (s as String).is_empty():
		return s as String
	return "Adjusts this simulation parameter; see scripts/constants.gd (GameConstants) for semantics."
