extends Node
## Runtime simulation parameters (mutable). Defaults match **`GameConstants`**; use **`reset_to_reference_defaults()`** to restore.
## Generated from **`constants.gd`** — keep in sync when adding constants.

const _Ref := preload("res://scripts/constants.gd")

var GRAIN_SIZE_MM = 3.0
var BLOCK_AIR = 0
var BLOCK_SAND = 1
var BLOCK_STONE = 2
var BLOCK_PACKED_SAND = 3
var SAND_LATERAL_SPILL_STACK_LIMIT = 6
var NEST_SPILL_LATERAL_EXCLUDE_RADIUS = 5
var WORKER_FOOD_STORE_DEPOSIT_MAX_H_DIST = 5.0
var WORKER_ENTRANCE_CLEAR_ENGAGE_DIST = 14.0
var TICKS_PER_GAME_SECOND = 1
var GAME_SECONDS_PER_ANT_DAY = 60
var GAME_DAYS_PER_ANT_WEEK = 7
var EGG_DURATION_DAYS = 10
var LARVA_DURATION_DAYS = 14
var PUPA_DURATION_DAYS = 10
var QUEEN_CLAUSTRAL_EGG_BATCH_MIN = 3
var QUEEN_CLAUSTRAL_EGG_BATCH_MAX = 6
var QUEEN_EGG_CANNIBAL_ENERGY_GAIN = 0.06
var QUEEN_LARVA_FEED_ENERGY_COST = 0.003
var QUEEN_LARVA_FEED_PER_TICK = 0.00012
var QUEEN_LARVA_FEED_ENERGY_PER_LARVA_PER_TICK = 0.0
var WORKER_BROOD_CARE_PER_TICK = 0.00011
var QUEEN_TROPHALLAXIS_BASE_PER_TICK = 0.000018
var QUEEN_TROPHALLAXIS_PER_WORKER_SQRT = 0.0000055
var QUEEN_TROPHALLAXIS_SUGAR_FRACTION = 0.52
var QUEEN_TROPHALLAXIS_PROTEIN_FRACTION = 0.48
var QUEEN_TROPHALLAXIS_ENERGY_PER_UNIT_FOOD = 0.34
var QUEEN_VISUAL_SCALE = 6.0
var WORKER_VISUAL_SCALE = 3.0
var NANITIC_VISUAL_SCALE = 2.1
var PHEROMONE_CELL_SIZE = 2
var PHEROMONE_BASE_DEPOSIT = 0.32
var PHEROMONE_DEPOSIT_AMOUNT = 0.34
var PHEROMONE_EVAPORATION_RATE = 0.996
var PHEROMONE_DIFFUSION_LAMBDA = 0.15
var PHEROMONE_EVAPORATION_INTERVAL_TICKS = 72
var PHEROMONE_RECRUIT_THRESHOLD = 0.011
var PHEROMONE_MINIMUM_THRESHOLD = 0.0012
var PHEROMONE_SENSE_RADIUS = 4
var PHEROMONE_TROPOTAXIS_FLOOR = 0.001
var TRAIL_SATIATED_DEPOSIT_PROBABILITY = 0.55
var RECRUIT_TRAIL_PER_STEP_FRACTION = 0.16
var RECRUIT_TRAIL_FOLLOW_LOCAL_RADIUS = 3
var RECRUIT_TRAIL_EXIT_SCOUT_FACTOR = 0.32
var PHEROMONE_EXPLOITATION_THRESHOLD = 0.015
var FOOTPRINT_SEARCH_ATTRACTION_WEIGHT = 0.35
var FEEDER_CROWD_RADIUS = 2
var FEEDER_CROWD_MAX_WORKERS = 4
var FEEDER_CROWD_OVERFLOW_ATTEMPT_PROB = 0.12
var FORAGING_MEMORY_TRAIL_WEAK = 0.009
var FORAGING_MEMORY_BIAS_WEIGHT = 1.8
var TROPOTAXIS_RATIO_EPS = 0.012
var TROPOTAXIS_RATIO_GAIN = 0.34
var TROPOTAXIS_HC_DENOM_SCALE = 1.12
var TROPOTAXIS_CROWD_PER_ANT = 0.38
var RECRUIT_TRAIL_BEACON_EXTRA_MULT = 22.0
var RECRUIT_TRAIL_BEACON_DECAY_MM = 28.0
var RECRUIT_TRAIL_BEACON_FLOOR = 1.85
var HOME_RANGE_FOOTPRINT_THRESHOLD = 0.032
var FORAGING_MARKED_INTERVAL_MULT = 0.87
var NAIVE_ZIGZAG_INTERVAL_MIN = 1.08
var NAIVE_ZIGZAG_INTERVAL_MAX = 1.42
var SCOUT_SEARCH_STOP_PROBABILITY = 0.085
var VALIDATION_EXPORT_ENABLED = true
var VALIDATION_EXPORT_INTERVAL_TICKS = 60
var ALARM_DEPOSIT_ON_CRITICAL = 0.42
var ALARM_EVAPORATION_RATE = 0.88
var ALARM_EVAPORATION_INTERVAL_TICKS = 8
var ALARM_MINIMUM_THRESHOLD = 0.002
var PHEROMONE_VIS_RECRUITMENT = Color(0.12, 0.82, 0.38, 1.0)
var PHEROMONE_VIS_FOOTPRINT = Color(0.88, 0.28, 0.72, 1.0)
var FOOTPRINT_OVERLAY_MIN_CONC = 0.028
var PHEROMONE_VIS_BUILDING = Color(0.96, 0.74, 0.18, 1.0)
var PHEROMONE_VIS_ALARM = Color(0.95, 0.35, 0.12, 1.0)
var TRAIL_SATURATION_START = 0.42
var TRAIL_SATURATION_MIN_DEPOSIT_SCALE = 0.28
var FOOTPRINT_DEPOSIT_PER_STEP = 0.0011
var FOOTPRINT_EVAPORATION_RATE = 0.988
var FOOTPRINT_EVAPORATION_INTERVAL_TICKS = 48
var FOOTPRINT_MINIMUM_THRESHOLD = 0.0006
var FOOTPRINT_REPULSION_WEIGHT = 2.2
var FOOTPRINT_SCOUT_BASE_WEIGHT = 0.002
var FOOTPRINT_SCOUT_REPULSION_MULT = 1.4
var FOOD_STORE_TARGET_SUGAR = 200.0
var FOOD_STORE_TARGET_PROTEIN = 150.0
var MIN_FORAGER_FRACTION = 0.15
var SCOUT_MAX_TURN_DEG_PER_STEP = 25.0
var SCOUT_MIN_SEARCH_RADIUS = 15.0
var FOOD_CARRY_AMOUNT = 0.04
var FOOD_APHID_SUPPLY_MIN = 0.38
var FOOD_APHID_SUPPLY_MAX = 1.18
var FOOD_INSECT_SUPPLY_MIN = 0.22
var FOOD_INSECT_SUPPLY_MAX = 0.88
var FOOD_SEED_SUPPLY_MIN = 0.18
var FOOD_SEED_SUPPLY_MAX = 0.62
var FOOD_SPAWN_FIRST_DELAY_MIN = 90
var FOOD_SPAWN_FIRST_DELAY_MAX = 420
var FOOD_SPAWN_INTERVAL_TICKS_MIN = 400
var FOOD_SPAWN_INTERVAL_TICKS_MAX = 2200
var FOOD_MAX_ACTIVE_SOURCES = 36
var FOOD_SPAWN_MIN_DIST_FROM_NEST = 28
var FOOD_VISUAL_BASE_SCALE_MIN = 0.82
var FOOD_VISUAL_BASE_SCALE_MAX = 1.12
var FOOD_VISUAL_MIN_SCALE_RATIO = 0.14
var FOOD_CRITICAL_THRESHOLD = 0.15
var COMPACTION_RADIUS = 1
var PACKED_SAND_DIG_MULTIPLIER = 2
var PACKED_SAND_COLOR = Color(0.72, 0.60, 0.38)
var DIG_ACT_DURATION_TICKS = 3
var TUNNEL_YIELD_TICKS = 5
var SPOIL_DEPOSIT_RADIUS = 24
var SPOIL_DEPOSIT_INNER_CLEAR = 3.5
var MAX_SPOIL_HEIGHT = 6
var MAX_NEST_BUILDERS = 8
var VOLUME_PER_WORKER = 24
var MAX_DIG_DEPTH = 150
var MIN_GALLERY_WIDTH = 4
var MIN_GALLERY_HEIGHT = 4
var MIN_SHAFT_WIDTH = 6
var MIN_BROOD_CHAMBER_DIAMETER = 8
var QUEEN_CHAMBER_DIAMETER = 10
var QUEEN_CHAMBER_HEIGHT = 8
var QUEEN_PERMANENT_CHAMBER_DIAMETER = 14
var SHAFT_TARGET_DEPTH = 14
var DEPTH_WEIGHT_ENTRY = 1.2
var DEPTH_WEIGHT_CHAMBER = 2.0
var DEPTH_ATTRACTION_FALLOFF = 0.15
var MAX_GALLERY_RADIUS = 20
var HORIZONTAL_WEIGHT = 1.8
var TUNNEL_CONTINUE_BONUS = 2.5
var CROWDING_PENALTY = 5.0
var NOISE_AMPLITUDE = 0.5
var BLUEPRINT_WEIGHT = 1.5
var RADIAL_OUTWARD_BIAS = 2.0
var TUNNEL_EXTEND_BIAS = 3.0
var NEST_SHAFT_AXIS_RADIUS_VOX = 5
var NEST_SHAFT_AXIS_ENTRY_PULL_SCALE = 0.32
var NEST_LATERAL_MIN_AXIS_DIST = 4.0
var NEST_LATERAL_EXPANSION_BONUS = 6.0
var NEST_DEEPEN_BELOW_DEEPEST_PENALTY = 5.0
var NEST_GALLERY_BRANCH_NOISE = 1.1
var NEST_GALLERY_SAMPLE_BOOST = 48
var NEST_SUBSTRATE_HARDNESS_MIN = 1.0
var NEST_SUBSTRATE_HARDNESS_MAX = 1.38
var NEST_BLUEPRINT_DIST_MIN = 4
var NEST_BLUEPRINT_DIST_MAX = 9
var NEST_BLUEPRINT_GLOBAL_ROT_MAX = 6.28318530718
var NEST_BLUEPRINT_ANGLE_JITTER = 0.5
var NEST_BLUEPRINT_SPUR_PROB = 0.34
var NEST_BLUEPRINT_LEAD_WEIGHT = 0.24
var BUILD_PHEROMONE_DEPOSIT_AMOUNT = 0.4
var BUILD_PHEROMONE_EVAPORATION_RATE = 0.96
var BUILD_PHEROMONE_EVAPORATION_INTERVAL_TICKS = 24
var BUILD_PHEROMONE_MINIMUM = 0.01
var FOUNDING_SHAFT_DEPTH = 14
var FOUNDING_SHAFT_WIDTH = 6
var FOUNDING_CHAMBER_SIZE = Vector3i(10, 8, 10)
var QUEEN_BFS_AIR_MAX_NODES = 4096
var PATH_TO_SURFACE_MAX_STEPS = 200
var QUEEN_SPOIL_DEPOSIT_SAMPLES = 16
var TRAIL_COVER_BUILD_PROB = 0.05
var XRAY_SAND_ALPHA = 0.18
var XRAY_DEPTH_FADE_RANGE = 80.0
var FAST_FORWARD_SIM_STEPS_CAP = 120
var SIM_SUBSTEP_THROTTLE_MIN_WORKERS = 50
var SIM_SUBSTEP_WORKER_BUDGET = 5200
var SIM_SUBSTEP_MIN = 10
var PHEROMONE_MAX_DIFFUSION_PASSES_PER_FRAME = 1
var TRAIL_OVERLAY_REFRESH_BASE = 15
var TRAIL_OVERLAY_REFRESH_SLOW = 55
var TRAIL_OVERLAY_THROTTLE_WORKER_THRESHOLD = 140
var WORKER_MOVE_INTERVAL = 0.45
var QUEEN_SEARCH_MOVE_INTERVAL = 0.8
var QUEEN_DIG_ACT_TICK_INTERVAL = 0.45
var QUEEN_FLY_IN_DURATION = 4.0
var QUEEN_WING_SHED_DURATION = 2.0
var QUEEN_SEARCH_DURATION_MIN = 10.0
var QUEEN_SEARCH_DURATION_MAX = 20.0
var FAST_FORWARD_SPEEDS: Array[float] = [10.0, 30.0, 60.0, 120.0]

var MM_PER_UNIT: float:
	get: return GRAIN_SIZE_MM

var TICKS_PER_ANT_DAY: int:
	get: return GAME_SECONDS_PER_ANT_DAY * 30

var EGG_DURATION_TICKS: int:
	get: return EGG_DURATION_DAYS * TICKS_PER_ANT_DAY

var LARVA_DURATION_TICKS: int:
	get: return LARVA_DURATION_DAYS * TICKS_PER_ANT_DAY

var PUPA_DURATION_TICKS: int:
	get: return PUPA_DURATION_DAYS * TICKS_PER_ANT_DAY

var QUEEN_CLAUSTRAL_EGG_INTERVAL_TICKS: int:
	get: return 4 * TICKS_PER_ANT_DAY

var QUEEN_ESTABLISHED_EGG_INTERVAL_TICKS: int:
	get: return 2 * TICKS_PER_ANT_DAY

var QUEEN_CLAUSTRAL_ENERGY_DRAIN_PER_TICK: float:
	get: return 1.0 / float(55 * TICKS_PER_ANT_DAY)

var YOUNG_WORKER_AGE_THRESHOLD: int:
	get: return 10 * TICKS_PER_ANT_DAY

var CALLOW_DARKEN_TICKS: int:
	get: return 3 * TICKS_PER_ANT_DAY

var FOOD_SPOIL_DURATION_TICKS_MIN: int:
	get: return 2 * TICKS_PER_ANT_DAY

var FOOD_SPOIL_DURATION_TICKS_MAX: int:
	get: return 14 * TICKS_PER_ANT_DAY


func reset_to_reference_defaults() -> void:
	GRAIN_SIZE_MM = _Ref.GRAIN_SIZE_MM
	BLOCK_AIR = _Ref.BLOCK_AIR
	BLOCK_SAND = _Ref.BLOCK_SAND
	BLOCK_STONE = _Ref.BLOCK_STONE
	BLOCK_PACKED_SAND = _Ref.BLOCK_PACKED_SAND
	SAND_LATERAL_SPILL_STACK_LIMIT = _Ref.SAND_LATERAL_SPILL_STACK_LIMIT
	NEST_SPILL_LATERAL_EXCLUDE_RADIUS = _Ref.NEST_SPILL_LATERAL_EXCLUDE_RADIUS
	WORKER_FOOD_STORE_DEPOSIT_MAX_H_DIST = _Ref.WORKER_FOOD_STORE_DEPOSIT_MAX_H_DIST
	WORKER_ENTRANCE_CLEAR_ENGAGE_DIST = _Ref.WORKER_ENTRANCE_CLEAR_ENGAGE_DIST
	TICKS_PER_GAME_SECOND = _Ref.TICKS_PER_GAME_SECOND
	GAME_SECONDS_PER_ANT_DAY = _Ref.GAME_SECONDS_PER_ANT_DAY
	GAME_DAYS_PER_ANT_WEEK = _Ref.GAME_DAYS_PER_ANT_WEEK
	EGG_DURATION_DAYS = _Ref.EGG_DURATION_DAYS
	LARVA_DURATION_DAYS = _Ref.LARVA_DURATION_DAYS
	PUPA_DURATION_DAYS = _Ref.PUPA_DURATION_DAYS
	QUEEN_CLAUSTRAL_EGG_BATCH_MIN = _Ref.QUEEN_CLAUSTRAL_EGG_BATCH_MIN
	QUEEN_CLAUSTRAL_EGG_BATCH_MAX = _Ref.QUEEN_CLAUSTRAL_EGG_BATCH_MAX
	QUEEN_EGG_CANNIBAL_ENERGY_GAIN = _Ref.QUEEN_EGG_CANNIBAL_ENERGY_GAIN
	QUEEN_LARVA_FEED_ENERGY_COST = _Ref.QUEEN_LARVA_FEED_ENERGY_COST
	QUEEN_LARVA_FEED_PER_TICK = _Ref.QUEEN_LARVA_FEED_PER_TICK
	QUEEN_LARVA_FEED_ENERGY_PER_LARVA_PER_TICK = _Ref.QUEEN_LARVA_FEED_ENERGY_PER_LARVA_PER_TICK
	WORKER_BROOD_CARE_PER_TICK = _Ref.WORKER_BROOD_CARE_PER_TICK
	QUEEN_TROPHALLAXIS_BASE_PER_TICK = _Ref.QUEEN_TROPHALLAXIS_BASE_PER_TICK
	QUEEN_TROPHALLAXIS_PER_WORKER_SQRT = _Ref.QUEEN_TROPHALLAXIS_PER_WORKER_SQRT
	QUEEN_TROPHALLAXIS_SUGAR_FRACTION = _Ref.QUEEN_TROPHALLAXIS_SUGAR_FRACTION
	QUEEN_TROPHALLAXIS_PROTEIN_FRACTION = _Ref.QUEEN_TROPHALLAXIS_PROTEIN_FRACTION
	QUEEN_TROPHALLAXIS_ENERGY_PER_UNIT_FOOD = _Ref.QUEEN_TROPHALLAXIS_ENERGY_PER_UNIT_FOOD
	QUEEN_VISUAL_SCALE = _Ref.QUEEN_VISUAL_SCALE
	WORKER_VISUAL_SCALE = _Ref.WORKER_VISUAL_SCALE
	NANITIC_VISUAL_SCALE = _Ref.NANITIC_VISUAL_SCALE
	PHEROMONE_CELL_SIZE = _Ref.PHEROMONE_CELL_SIZE
	PHEROMONE_BASE_DEPOSIT = _Ref.PHEROMONE_BASE_DEPOSIT
	PHEROMONE_DEPOSIT_AMOUNT = _Ref.PHEROMONE_DEPOSIT_AMOUNT
	PHEROMONE_EVAPORATION_RATE = _Ref.PHEROMONE_EVAPORATION_RATE
	PHEROMONE_DIFFUSION_LAMBDA = _Ref.PHEROMONE_DIFFUSION_LAMBDA
	PHEROMONE_EVAPORATION_INTERVAL_TICKS = _Ref.PHEROMONE_EVAPORATION_INTERVAL_TICKS
	PHEROMONE_RECRUIT_THRESHOLD = _Ref.PHEROMONE_RECRUIT_THRESHOLD
	PHEROMONE_MINIMUM_THRESHOLD = _Ref.PHEROMONE_MINIMUM_THRESHOLD
	PHEROMONE_SENSE_RADIUS = _Ref.PHEROMONE_SENSE_RADIUS
	PHEROMONE_TROPOTAXIS_FLOOR = _Ref.PHEROMONE_TROPOTAXIS_FLOOR
	TRAIL_SATIATED_DEPOSIT_PROBABILITY = _Ref.TRAIL_SATIATED_DEPOSIT_PROBABILITY
	RECRUIT_TRAIL_PER_STEP_FRACTION = _Ref.RECRUIT_TRAIL_PER_STEP_FRACTION
	RECRUIT_TRAIL_FOLLOW_LOCAL_RADIUS = _Ref.RECRUIT_TRAIL_FOLLOW_LOCAL_RADIUS
	RECRUIT_TRAIL_EXIT_SCOUT_FACTOR = _Ref.RECRUIT_TRAIL_EXIT_SCOUT_FACTOR
	PHEROMONE_EXPLOITATION_THRESHOLD = _Ref.PHEROMONE_EXPLOITATION_THRESHOLD
	FOOTPRINT_SEARCH_ATTRACTION_WEIGHT = _Ref.FOOTPRINT_SEARCH_ATTRACTION_WEIGHT
	FEEDER_CROWD_RADIUS = _Ref.FEEDER_CROWD_RADIUS
	FEEDER_CROWD_MAX_WORKERS = _Ref.FEEDER_CROWD_MAX_WORKERS
	FEEDER_CROWD_OVERFLOW_ATTEMPT_PROB = _Ref.FEEDER_CROWD_OVERFLOW_ATTEMPT_PROB
	FORAGING_MEMORY_TRAIL_WEAK = _Ref.FORAGING_MEMORY_TRAIL_WEAK
	FORAGING_MEMORY_BIAS_WEIGHT = _Ref.FORAGING_MEMORY_BIAS_WEIGHT
	TROPOTAXIS_RATIO_EPS = _Ref.TROPOTAXIS_RATIO_EPS
	TROPOTAXIS_RATIO_GAIN = _Ref.TROPOTAXIS_RATIO_GAIN
	TROPOTAXIS_HC_DENOM_SCALE = _Ref.TROPOTAXIS_HC_DENOM_SCALE
	TROPOTAXIS_CROWD_PER_ANT = _Ref.TROPOTAXIS_CROWD_PER_ANT
	RECRUIT_TRAIL_BEACON_EXTRA_MULT = _Ref.RECRUIT_TRAIL_BEACON_EXTRA_MULT
	RECRUIT_TRAIL_BEACON_DECAY_MM = _Ref.RECRUIT_TRAIL_BEACON_DECAY_MM
	RECRUIT_TRAIL_BEACON_FLOOR = _Ref.RECRUIT_TRAIL_BEACON_FLOOR
	HOME_RANGE_FOOTPRINT_THRESHOLD = _Ref.HOME_RANGE_FOOTPRINT_THRESHOLD
	FORAGING_MARKED_INTERVAL_MULT = _Ref.FORAGING_MARKED_INTERVAL_MULT
	NAIVE_ZIGZAG_INTERVAL_MIN = _Ref.NAIVE_ZIGZAG_INTERVAL_MIN
	NAIVE_ZIGZAG_INTERVAL_MAX = _Ref.NAIVE_ZIGZAG_INTERVAL_MAX
	SCOUT_SEARCH_STOP_PROBABILITY = _Ref.SCOUT_SEARCH_STOP_PROBABILITY
	VALIDATION_EXPORT_ENABLED = _Ref.VALIDATION_EXPORT_ENABLED
	VALIDATION_EXPORT_INTERVAL_TICKS = _Ref.VALIDATION_EXPORT_INTERVAL_TICKS
	ALARM_DEPOSIT_ON_CRITICAL = _Ref.ALARM_DEPOSIT_ON_CRITICAL
	ALARM_EVAPORATION_RATE = _Ref.ALARM_EVAPORATION_RATE
	ALARM_EVAPORATION_INTERVAL_TICKS = _Ref.ALARM_EVAPORATION_INTERVAL_TICKS
	ALARM_MINIMUM_THRESHOLD = _Ref.ALARM_MINIMUM_THRESHOLD
	PHEROMONE_VIS_RECRUITMENT = _Ref.PHEROMONE_VIS_RECRUITMENT
	PHEROMONE_VIS_FOOTPRINT = _Ref.PHEROMONE_VIS_FOOTPRINT
	FOOTPRINT_OVERLAY_MIN_CONC = _Ref.FOOTPRINT_OVERLAY_MIN_CONC
	PHEROMONE_VIS_BUILDING = _Ref.PHEROMONE_VIS_BUILDING
	PHEROMONE_VIS_ALARM = _Ref.PHEROMONE_VIS_ALARM
	TRAIL_SATURATION_START = _Ref.TRAIL_SATURATION_START
	TRAIL_SATURATION_MIN_DEPOSIT_SCALE = _Ref.TRAIL_SATURATION_MIN_DEPOSIT_SCALE
	FOOTPRINT_DEPOSIT_PER_STEP = _Ref.FOOTPRINT_DEPOSIT_PER_STEP
	FOOTPRINT_EVAPORATION_RATE = _Ref.FOOTPRINT_EVAPORATION_RATE
	FOOTPRINT_EVAPORATION_INTERVAL_TICKS = _Ref.FOOTPRINT_EVAPORATION_INTERVAL_TICKS
	FOOTPRINT_MINIMUM_THRESHOLD = _Ref.FOOTPRINT_MINIMUM_THRESHOLD
	FOOTPRINT_REPULSION_WEIGHT = _Ref.FOOTPRINT_REPULSION_WEIGHT
	FOOTPRINT_SCOUT_BASE_WEIGHT = _Ref.FOOTPRINT_SCOUT_BASE_WEIGHT
	FOOTPRINT_SCOUT_REPULSION_MULT = _Ref.FOOTPRINT_SCOUT_REPULSION_MULT
	FOOD_STORE_TARGET_SUGAR = _Ref.FOOD_STORE_TARGET_SUGAR
	FOOD_STORE_TARGET_PROTEIN = _Ref.FOOD_STORE_TARGET_PROTEIN
	MIN_FORAGER_FRACTION = _Ref.MIN_FORAGER_FRACTION
	SCOUT_MAX_TURN_DEG_PER_STEP = _Ref.SCOUT_MAX_TURN_DEG_PER_STEP
	SCOUT_MIN_SEARCH_RADIUS = _Ref.SCOUT_MIN_SEARCH_RADIUS
	FOOD_CARRY_AMOUNT = _Ref.FOOD_CARRY_AMOUNT
	FOOD_APHID_SUPPLY_MIN = _Ref.FOOD_APHID_SUPPLY_MIN
	FOOD_APHID_SUPPLY_MAX = _Ref.FOOD_APHID_SUPPLY_MAX
	FOOD_INSECT_SUPPLY_MIN = _Ref.FOOD_INSECT_SUPPLY_MIN
	FOOD_INSECT_SUPPLY_MAX = _Ref.FOOD_INSECT_SUPPLY_MAX
	FOOD_SEED_SUPPLY_MIN = _Ref.FOOD_SEED_SUPPLY_MIN
	FOOD_SEED_SUPPLY_MAX = _Ref.FOOD_SEED_SUPPLY_MAX
	FOOD_SPAWN_FIRST_DELAY_MIN = _Ref.FOOD_SPAWN_FIRST_DELAY_MIN
	FOOD_SPAWN_FIRST_DELAY_MAX = _Ref.FOOD_SPAWN_FIRST_DELAY_MAX
	FOOD_SPAWN_INTERVAL_TICKS_MIN = _Ref.FOOD_SPAWN_INTERVAL_TICKS_MIN
	FOOD_SPAWN_INTERVAL_TICKS_MAX = _Ref.FOOD_SPAWN_INTERVAL_TICKS_MAX
	FOOD_MAX_ACTIVE_SOURCES = _Ref.FOOD_MAX_ACTIVE_SOURCES
	FOOD_SPAWN_MIN_DIST_FROM_NEST = _Ref.FOOD_SPAWN_MIN_DIST_FROM_NEST
	FOOD_VISUAL_BASE_SCALE_MIN = _Ref.FOOD_VISUAL_BASE_SCALE_MIN
	FOOD_VISUAL_BASE_SCALE_MAX = _Ref.FOOD_VISUAL_BASE_SCALE_MAX
	FOOD_VISUAL_MIN_SCALE_RATIO = _Ref.FOOD_VISUAL_MIN_SCALE_RATIO
	FOOD_CRITICAL_THRESHOLD = _Ref.FOOD_CRITICAL_THRESHOLD
	COMPACTION_RADIUS = _Ref.COMPACTION_RADIUS
	PACKED_SAND_DIG_MULTIPLIER = _Ref.PACKED_SAND_DIG_MULTIPLIER
	PACKED_SAND_COLOR = _Ref.PACKED_SAND_COLOR
	DIG_ACT_DURATION_TICKS = _Ref.DIG_ACT_DURATION_TICKS
	TUNNEL_YIELD_TICKS = _Ref.TUNNEL_YIELD_TICKS
	SPOIL_DEPOSIT_RADIUS = _Ref.SPOIL_DEPOSIT_RADIUS
	SPOIL_DEPOSIT_INNER_CLEAR = _Ref.SPOIL_DEPOSIT_INNER_CLEAR
	MAX_SPOIL_HEIGHT = _Ref.MAX_SPOIL_HEIGHT
	MAX_NEST_BUILDERS = _Ref.MAX_NEST_BUILDERS
	VOLUME_PER_WORKER = _Ref.VOLUME_PER_WORKER
	MAX_DIG_DEPTH = _Ref.MAX_DIG_DEPTH
	MIN_GALLERY_WIDTH = _Ref.MIN_GALLERY_WIDTH
	MIN_GALLERY_HEIGHT = _Ref.MIN_GALLERY_HEIGHT
	MIN_SHAFT_WIDTH = _Ref.MIN_SHAFT_WIDTH
	MIN_BROOD_CHAMBER_DIAMETER = _Ref.MIN_BROOD_CHAMBER_DIAMETER
	QUEEN_CHAMBER_DIAMETER = _Ref.QUEEN_CHAMBER_DIAMETER
	QUEEN_CHAMBER_HEIGHT = _Ref.QUEEN_CHAMBER_HEIGHT
	QUEEN_PERMANENT_CHAMBER_DIAMETER = _Ref.QUEEN_PERMANENT_CHAMBER_DIAMETER
	SHAFT_TARGET_DEPTH = _Ref.SHAFT_TARGET_DEPTH
	DEPTH_WEIGHT_ENTRY = _Ref.DEPTH_WEIGHT_ENTRY
	DEPTH_WEIGHT_CHAMBER = _Ref.DEPTH_WEIGHT_CHAMBER
	DEPTH_ATTRACTION_FALLOFF = _Ref.DEPTH_ATTRACTION_FALLOFF
	MAX_GALLERY_RADIUS = _Ref.MAX_GALLERY_RADIUS
	HORIZONTAL_WEIGHT = _Ref.HORIZONTAL_WEIGHT
	TUNNEL_CONTINUE_BONUS = _Ref.TUNNEL_CONTINUE_BONUS
	CROWDING_PENALTY = _Ref.CROWDING_PENALTY
	NOISE_AMPLITUDE = _Ref.NOISE_AMPLITUDE
	BLUEPRINT_WEIGHT = _Ref.BLUEPRINT_WEIGHT
	RADIAL_OUTWARD_BIAS = _Ref.RADIAL_OUTWARD_BIAS
	TUNNEL_EXTEND_BIAS = _Ref.TUNNEL_EXTEND_BIAS
	NEST_SHAFT_AXIS_RADIUS_VOX = _Ref.NEST_SHAFT_AXIS_RADIUS_VOX
	NEST_SHAFT_AXIS_ENTRY_PULL_SCALE = _Ref.NEST_SHAFT_AXIS_ENTRY_PULL_SCALE
	NEST_LATERAL_MIN_AXIS_DIST = _Ref.NEST_LATERAL_MIN_AXIS_DIST
	NEST_LATERAL_EXPANSION_BONUS = _Ref.NEST_LATERAL_EXPANSION_BONUS
	NEST_DEEPEN_BELOW_DEEPEST_PENALTY = _Ref.NEST_DEEPEN_BELOW_DEEPEST_PENALTY
	NEST_GALLERY_BRANCH_NOISE = _Ref.NEST_GALLERY_BRANCH_NOISE
	NEST_GALLERY_SAMPLE_BOOST = _Ref.NEST_GALLERY_SAMPLE_BOOST
	NEST_SUBSTRATE_HARDNESS_MIN = _Ref.NEST_SUBSTRATE_HARDNESS_MIN
	NEST_SUBSTRATE_HARDNESS_MAX = _Ref.NEST_SUBSTRATE_HARDNESS_MAX
	NEST_BLUEPRINT_DIST_MIN = _Ref.NEST_BLUEPRINT_DIST_MIN
	NEST_BLUEPRINT_DIST_MAX = _Ref.NEST_BLUEPRINT_DIST_MAX
	NEST_BLUEPRINT_GLOBAL_ROT_MAX = _Ref.NEST_BLUEPRINT_GLOBAL_ROT_MAX
	NEST_BLUEPRINT_ANGLE_JITTER = _Ref.NEST_BLUEPRINT_ANGLE_JITTER
	NEST_BLUEPRINT_SPUR_PROB = _Ref.NEST_BLUEPRINT_SPUR_PROB
	NEST_BLUEPRINT_LEAD_WEIGHT = _Ref.NEST_BLUEPRINT_LEAD_WEIGHT
	BUILD_PHEROMONE_DEPOSIT_AMOUNT = _Ref.BUILD_PHEROMONE_DEPOSIT_AMOUNT
	BUILD_PHEROMONE_EVAPORATION_RATE = _Ref.BUILD_PHEROMONE_EVAPORATION_RATE
	BUILD_PHEROMONE_EVAPORATION_INTERVAL_TICKS = _Ref.BUILD_PHEROMONE_EVAPORATION_INTERVAL_TICKS
	BUILD_PHEROMONE_MINIMUM = _Ref.BUILD_PHEROMONE_MINIMUM
	FOUNDING_SHAFT_DEPTH = _Ref.FOUNDING_SHAFT_DEPTH
	FOUNDING_SHAFT_WIDTH = _Ref.FOUNDING_SHAFT_WIDTH
	FOUNDING_CHAMBER_SIZE = _Ref.FOUNDING_CHAMBER_SIZE
	QUEEN_BFS_AIR_MAX_NODES = _Ref.QUEEN_BFS_AIR_MAX_NODES
	PATH_TO_SURFACE_MAX_STEPS = _Ref.PATH_TO_SURFACE_MAX_STEPS
	QUEEN_SPOIL_DEPOSIT_SAMPLES = _Ref.QUEEN_SPOIL_DEPOSIT_SAMPLES
	TRAIL_COVER_BUILD_PROB = _Ref.TRAIL_COVER_BUILD_PROB
	XRAY_SAND_ALPHA = _Ref.XRAY_SAND_ALPHA
	XRAY_DEPTH_FADE_RANGE = _Ref.XRAY_DEPTH_FADE_RANGE
	FAST_FORWARD_SIM_STEPS_CAP = _Ref.FAST_FORWARD_SIM_STEPS_CAP
	SIM_SUBSTEP_THROTTLE_MIN_WORKERS = _Ref.SIM_SUBSTEP_THROTTLE_MIN_WORKERS
	SIM_SUBSTEP_WORKER_BUDGET = _Ref.SIM_SUBSTEP_WORKER_BUDGET
	SIM_SUBSTEP_MIN = _Ref.SIM_SUBSTEP_MIN
	PHEROMONE_MAX_DIFFUSION_PASSES_PER_FRAME = _Ref.PHEROMONE_MAX_DIFFUSION_PASSES_PER_FRAME
	TRAIL_OVERLAY_REFRESH_BASE = _Ref.TRAIL_OVERLAY_REFRESH_BASE
	TRAIL_OVERLAY_REFRESH_SLOW = _Ref.TRAIL_OVERLAY_REFRESH_SLOW
	TRAIL_OVERLAY_THROTTLE_WORKER_THRESHOLD = _Ref.TRAIL_OVERLAY_THROTTLE_WORKER_THRESHOLD
	WORKER_MOVE_INTERVAL = _Ref.WORKER_MOVE_INTERVAL
	QUEEN_SEARCH_MOVE_INTERVAL = _Ref.QUEEN_SEARCH_MOVE_INTERVAL
	QUEEN_DIG_ACT_TICK_INTERVAL = _Ref.QUEEN_DIG_ACT_TICK_INTERVAL
	QUEEN_FLY_IN_DURATION = _Ref.QUEEN_FLY_IN_DURATION
	QUEEN_WING_SHED_DURATION = _Ref.QUEEN_WING_SHED_DURATION
	QUEEN_SEARCH_DURATION_MIN = _Ref.QUEEN_SEARCH_DURATION_MIN
	QUEEN_SEARCH_DURATION_MAX = _Ref.QUEEN_SEARCH_DURATION_MAX
	FAST_FORWARD_SPEEDS = _Ref.FAST_FORWARD_SPEEDS.duplicate()
